### ISSUE TITLE
Image of skin weapon item is incorrectly printed.

### ISSUE THREAD

**Issue by DebugBios** [Ochii/cso2-launcher#57]
![cso2_0000](https://user-images.githubusercontent.com/44349391/54067517-4eff9600-4284-11e9-9d62-e3ba33eb6e1d.jpg)
![cso2_0001](https://user-images.githubusercontent.com/44349391/54067578-072d3e80-4285-11e9-97d2-7301ed9cba8c.jpg)

**Comment by dounai2333** [comment]
individual problems?

![%OI L)E{N9YH`ILU2P)0CRL](https://user-images.githubusercontent.com/45044404/54070529-f63bf780-429b-11e9-9dc8-8b02d8fd6875.png)
![G98}09OPI@M_7HFFH`BQDSX](https://user-images.githubusercontent.com/45044404/54070541-1a97d400-429c-11e9-8e1c-20c83159301b.png)
![RSV``QMAV6L_I32BJ1@FI1M](https://user-images.githubusercontent.com/45044404/54070544-1ff51e80-429c-11e9-94a3-5ec0088f2913.png)

some excessive packet loss will cause the skin to be applied incorrectly, but this will be fixed in 2 seconds
